# Use root/example as user/password credentials
version: '3.1'

services:

  spring-boot-thymeleaf:
    container_name: spring-boot-thymeleaf
    image: ghcr.io/ramiralvesmelo/spring-boot-thymeleaf/spring-boot-thymeleaf:latest
    environment:      
      SPRING_LDAP_URL: ldap://apacheds:10389
    ports:
      - 8081:8080
    depends_on:
      - apacheds

  apacheds:
    container_name: apacheds
    image: kadimasolutions/apacheds:latest
    tty: true 
    stdin_open: true
    ports:
     - 10389:10389
     - 10636:10636
    volumes:
     - apacheds-data:/opt/apacheds/instances/default

volumes:
  apacheds-data: