services:

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9099:9099
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9099,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9099
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181 

  kafka-producer:
    container_name: producer
    image: ghcr.io/ramiralvesmelo/spring-boot-kafka/kafka-producer:latest
    restart: always
    depends_on:
      - kafka
    ports:
      - 8081:8081
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9099
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181              
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9099

  kafka-cosumer:
    container_name: cosumer
    image: ghcr.io/ramiralvesmelo/spring-boot-kafka/kafka-consumer:latest
    restart: always
    depends_on:
      - kafka
    ports:
      - 8082:8082
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9099
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181  
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9099

